// <auto-generated />
namespace Tasks1To4.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddLicense : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddLicense));
        
        string IMigrationMetadata.Id
        {
            get { return "201704071104461_AddLicense"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
